enhance_research_outline:
  description: >
    Take a research outline input and provide strategic advice on improving it 
    by brainstorming ideas to complement the outline, supporting a
    stronger hypothesis and compelling narratives.
    This is the research outline, inside triple backticks: ```{r_outline}```
  expected_output: >
    Your output is an enhanced research outline that includes the 
    improvement recommendations accepted by the human user. The output is in markdown form.
  output_file: "../outputs/1. enhanced_research_outline.md"
  
plan_research:
  description: >
    Your task is to break down a provided research outline into more detailed and actionable research tasks. 
    Each subtask you create has a clear intention and goal that helps a researcher analyze and form an opinion. 
    You will give this detailed plan to your Tech Research Analyst. 
  expected_output: >
    A detailed research plan with actionable tasks, in markdown form. The plan includes, for each key idea, 
    URLs that serve as great relevant resources from which to base the research, the intent of the idea, and the
    reason why this idea is relevant in the overall research task.
  output_file: "../outputs/2. research_plan.md"

summarize_resources:
  description: >
    You execute a provided research plan to the fullest extent possible by summarizing resources (links). For each idea, resource, article, paper, etc specified
    in the plan, you visit the provided resource, read and analyze the information, and summarize the resource without a significant loss of
    fidelity and without overlooking key edge cases. You use your bulk web scrapper tool to ask for a summary of all the resources listed in the plan.
  expected_output: >
    A document that consolidates all the information you've researched. The document covers all the items specified in the research plan.
  output_file: "../outputs/3. resources_summary.md"

write_blog:
  description: >
    You take a research outline and summarized research outputs to produce an engaging blog post.
    This blog postis highly engaging for your audience of machine learning engineers, data scientists, 
    data analysts, and data engineers. The blog post follows the structure defined in the research outline.
  expected_output: >
    A blog post of around 3000 words, in a technical but informal language that's appealing to engineers in the tech industry.
    The output blog is in a markdown file. 
  output_file: "../outputs/4. blog.md"