FROM mcr.microsoft.com/devcontainers/python:1.1-3.11

# RUN sudo apt update && \
    # geckodriver
    # wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz && \
    # tar -xvzf geckodriver* && \
    # chmod +x geckodriver && \
    # mv geckodriver /usr/local/bin/ && \
    # other packages
    # sudo apt install -y \
    # firefox-esr \
    # speech-dispatcher \
    # tmux && \
    # install poetry
    # pip install poetry==1.1.13 
    # echo "hello world"

RUN sudo apt update && \
    pipx install poetry==1.8.3