dynaconf_merge = true

[general]
openai_api_key = "your-openai-api-key-here"

[web_search]
search_api_key = "your-google-api-key-here"

[content_analysis]
llm_api_key = "your-llm-api-key-here"

[report_generation]
llm_api_key = "your-llm-api-key-here"

[output_refinement]
llm_api_key = "your-llm-api-key-here"
