dynaconf_merge = true

[general]
openai_api_key = "your-openai-api-key-here"

[web_search]
serpapi_api_key = "your-serpapi-api-key"
google_api_key = "your-google-api-key"
google_cse_id = "your-google-cse-id"
bing_subscription_key = "your-bing-subscription-key"
brave_api_key = "your-brave-api-key"
tavily_api_key = "your-tavily-api-key"

# [content_analysis]
# llm_api_key = "your-llm-api-key-here"

# [report_generation]
# llm_api_key = "your-llm-api-key-here"

# [output_refinement]
# llm_api_key = "your-llm-api-key-here"
